FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o shotmaster-server .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/shotmaster-server .

EXPOSE 8080

CMD ["./shotmaster-server"]